### ISSUE TITLE
Node6 got Path must be a string error.

### ISSUE THREAD

**Issue by greengerong** [mrak/stubby4node#57]
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Object.getArgs (../node_modules/stubby/src/console/cli.js:141:38)
    at setupStartOptions (../node_modules/stubby/src/main.js:60:18)
    at Stubby.start (../node_modules/stubby/src/main.js:92:12)

Other node version works.

     $ node -v
      v6.1.0

**Comment by mrak** [comment]
Thank you. This was fixed on `master` but not published. 

`0.3.1` should fix this.

**Comment by wieringen** [comment]
Still have this problem

node -v
v6.3.0

"stubby": "^0.3.1",

**Comment by mrak** [comment]
@wieringen I'm not able to reproduce. Could you provide the full command you are using? Or if you are using the programmatic API, a code snippet that reproduces the error?

**Comment by mrak** [comment]
Could you post the output of `stubby --version`?

If not installed globally: `./node_modules/.bin/stubby --version`?
